# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_Screen_UI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from AddVectorDialog import addVectorDialog
from Deny_Popup import DenyDialog
from Filter import FilterScreen
from BrowseRootPopUp import BrowseScreen
from AssociatePopUp import AssociateVectorScreen
from Detecting_Changes import DetectingChangesScreen
from ExportGraph import ExportGraphScreen



class MainScreen(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(886, 622)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainPageTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.MainPageTabWidget.setGeometry(QtCore.QRect(0, 0, 871, 591))
        self.MainPageTabWidget.setObjectName("MainPageTabWidget")
        self.EventConfig = QtWidgets.QWidget()
        self.EventConfig.setObjectName("EventConfig")
        self.EventConfigStartDateSelector = QtWidgets.QDateEdit(self.EventConfig)
        self.EventConfigStartDateSelector.setGeometry(QtCore.QRect(420, 120, 110, 22))
        self.EventConfigStartDateSelector.setObjectName("EventConfigStartDateSelector")
        self.EventConfigStartTimeSelector = QtWidgets.QTimeEdit(self.EventConfig)
        self.EventConfigStartTimeSelector.setGeometry(QtCore.QRect(540, 120, 118, 22))
        self.EventConfigStartTimeSelector.setObjectName("EventConfigStartTimeSelector")
        self.EventConfigEndDateSelector = QtWidgets.QDateEdit(self.EventConfig)
        self.EventConfigEndDateSelector.setGeometry(QtCore.QRect(420, 200, 110, 22))
        self.EventConfigEndDateSelector.setObjectName("EventConfigEndDateSelector")
        self.EventConfigEndTimeSelector = QtWidgets.QTimeEdit(self.EventConfig)
        self.EventConfigEndTimeSelector.setGeometry(QtCore.QRect(540, 200, 118, 22))
        self.EventConfigEndTimeSelector.setObjectName("EventConfigEndTimeSelector")
        self.EventConfigBrowseBtn = QtWidgets.QPushButton(self.EventConfig)
        self.EventConfigBrowseBtn.setGeometry(QtCore.QRect(610, 60, 75, 31))
        self.EventConfigBrowseBtn.setObjectName("EventConfigBrowseBtn")
        self.EventConfigBrowseBtn.clicked.connect(self.showBrowseScreen)
        self.EventConfigAnalystList = QtWidgets.QListWidget(self.EventConfig)
        self.EventConfigAnalystList.setGeometry(QtCore.QRect(30, 100, 261, 101))
        self.EventConfigAnalystList.setObjectName("EventConfigAnalystList")
        item = QtWidgets.QListWidgetItem()
        self.EventConfigAnalystList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.EventConfigAnalystList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.EventConfigAnalystList.addItem(item)
        self.EventConfigVectorList = QtWidgets.QListWidget(self.EventConfig)
        self.EventConfigVectorList.setGeometry(QtCore.QRect(30, 300, 261, 131))
        self.EventConfigVectorList.setObjectName("EventConfigVectorList")
        item = QtWidgets.QListWidgetItem()
        self.EventConfigVectorList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.EventConfigVectorList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.EventConfigVectorList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.EventConfigVectorList.addItem(item)
        self.AddVectorBtn = QtWidgets.QPushButton(self.EventConfig)
        self.AddVectorBtn.setGeometry(QtCore.QRect(40, 440, 91, 31))
        self.AddVectorBtn.setObjectName("AddVectorBtn")
        self.AddVectorBtn.clicked.connect(self.showAddVectorDialog)
        self.RemoveVectorBtn = QtWidgets.QPushButton(self.EventConfig)
        self.RemoveVectorBtn.setGeometry(QtCore.QRect(160, 440, 121, 31))
        self.RemoveVectorBtn.setObjectName("RemoveVectorBtn")
        self.EventConfigBackBtn = QtWidgets.QPushButton(self.EventConfig)
        self.EventConfigBackBtn.setGeometry(QtCore.QRect(40, 482, 75, 31))
        self.EventConfigBackBtn.setObjectName("EventConfigBackBtn")
        self.EventConfigSaveBtn = QtWidgets.QPushButton(self.EventConfig)
        self.EventConfigSaveBtn.setGeometry(QtCore.QRect(130, 482, 75, 31))
        self.EventConfigSaveBtn.setObjectName("EventConfigSaveBtn")
        self.EventConfigDescription = QtWidgets.QTextEdit(self.EventConfig)
        self.EventConfigDescription.setGeometry(QtCore.QRect(30, 210, 241, 71))
        self.EventConfigDescription.setObjectName("EventConfigDescription")
        self.EventConfigNameEdit = QtWidgets.QLineEdit(self.EventConfig)
        self.EventConfigNameEdit.setGeometry(QtCore.QRect(30, 60, 211, 31))
        self.EventConfigNameEdit.setObjectName("EventConfigNameEdit")
        self.EventConfigStartDateLabel = QtWidgets.QLabel(self.EventConfig)
        self.EventConfigStartDateLabel.setGeometry(QtCore.QRect(420, 100, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.EventConfigStartDateLabel.setFont(font)
        self.EventConfigStartDateLabel.setObjectName("EventConfigStartDateLabel")
        self.EventConfigEndDateLabel = QtWidgets.QLabel(self.EventConfig)
        self.EventConfigEndDateLabel.setGeometry(QtCore.QRect(420, 180, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.EventConfigEndDateLabel.setFont(font)
        self.EventConfigEndDateLabel.setObjectName("EventConfigEndDateLabel")
        self.EventConfigStartTimeLabel = QtWidgets.QLabel(self.EventConfig)
        self.EventConfigStartTimeLabel.setGeometry(QtCore.QRect(540, 100, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.EventConfigStartTimeLabel.setFont(font)
        self.EventConfigStartTimeLabel.setObjectName("EventConfigStartTimeLabel")
        self.EventConfigEndTimeLabel = QtWidgets.QLabel(self.EventConfig)
        self.EventConfigEndTimeLabel.setGeometry(QtCore.QRect(540, 180, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.EventConfigEndTimeLabel.setFont(font)
        self.EventConfigEndTimeLabel.setObjectName("EventConfigEndTimeLabel")
        self.EventConfigRootDirLabel = QtWidgets.QLabel(self.EventConfig)
        self.EventConfigRootDirLabel.setGeometry(QtCore.QRect(380, 60, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.EventConfigRootDirLabel.setFont(font)
        self.EventConfigRootDirLabel.setObjectName("EventConfigRootDirLabel")
        self.EventConfigRootDirPath = QtWidgets.QPlainTextEdit(self.EventConfig)
        self.EventConfigRootDirPath.setGeometry(QtCore.QRect(490, 60, 111, 21))
        self.EventConfigRootDirPath.setObjectName("EventConfigRootDirPath")
        self.label = QtWidgets.QLabel(self.EventConfig)
        self.label.setGeometry(QtCore.QRect(30, 30, 171, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.EventConfig)
        self.label_2.setGeometry(QtCore.QRect(380, 30, 191, 16))
        self.label_2.setObjectName("label_2")
        self.MainPageTabWidget.addTab(self.EventConfig, "")
        self.LogIngest = QtWidgets.QWidget()
        self.LogIngest.setObjectName("LogIngest")
        self.LogIngestionIngestBtn = QtWidgets.QPushButton(self.LogIngest)
        self.LogIngestionIngestBtn.setGeometry(QtCore.QRect(310, 230, 91, 31))
        self.LogIngestionIngestBtn.setObjectName("LogIngestionIngestBtn")
        self.LogIngestionImportLogBtn = QtWidgets.QPushButton(self.LogIngest)
        self.LogIngestionImportLogBtn.setGeometry(QtCore.QRect(154, 232, 91, 31))
        self.LogIngestionImportLogBtn.setObjectName("LogIngestionImportLogBtn")
        self.LogIngestionIgnoreBtn = QtWidgets.QPushButton(self.LogIngest)
        self.LogIngestionIgnoreBtn.setGeometry(QtCore.QRect(30, 472, 75, 31))
        self.LogIngestionIgnoreBtn.setObjectName("LogIngestionIgnoreBtn")
        self.LogIngestionConfirmBtn = QtWidgets.QPushButton(self.LogIngest)
        self.LogIngestionConfirmBtn.setGeometry(QtCore.QRect(140, 472, 75, 31))
        self.LogIngestionConfirmBtn.setObjectName("LogIngestionConfirmBtn")
        self.LogIngestionWaitingTable = QtWidgets.QTableWidget(self.LogIngest)
        self.LogIngestionWaitingTable.setGeometry(QtCore.QRect(30, 40, 391, 181))
        self.LogIngestionWaitingTable.setObjectName("LogIngestionWaitingTable")
        self.LogIngestionWaitingTable.setColumnCount(7)
        self.LogIngestionWaitingTable.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.LogIngestionWaitingTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogIngestionWaitingTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogIngestionWaitingTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogIngestionWaitingTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogIngestionWaitingTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogIngestionWaitingTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogIngestionWaitingTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogIngestionWaitingTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogIngestionWaitingTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogIngestionWaitingTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogIngestionWaitingTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogIngestionWaitingTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogIngestionWaitingTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogIngestionWaitingTable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogIngestionWaitingTable.setItem(3, 1, item)
        self.LogIngestionEnforcementTable = QtWidgets.QTableWidget(self.LogIngest)
        self.LogIngestionEnforcementTable.setGeometry(QtCore.QRect(30, 290, 401, 171))
        self.LogIngestionEnforcementTable.setObjectName("LogIngestionEnforcementTable")
        self.LogIngestionEnforcementTable.setColumnCount(5)
        self.LogIngestionEnforcementTable.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.LogIngestionEnforcementTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogIngestionEnforcementTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogIngestionEnforcementTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogIngestionEnforcementTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogIngestionEnforcementTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogIngestionEnforcementTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogIngestionEnforcementTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogIngestionEnforcementTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogIngestionEnforcementTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogIngestionEnforcementTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogIngestionEnforcementTable.setHorizontalHeaderItem(4, item)
        self.LogIngestionWaitingValiLabel = QtWidgets.QLabel(self.LogIngest)
        self.LogIngestionWaitingValiLabel.setGeometry(QtCore.QRect(30, 16, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LogIngestionWaitingValiLabel.setFont(font)
        self.LogIngestionWaitingValiLabel.setObjectName("LogIngestionWaitingValiLabel")
        self.LogIngestionEnforcementLabel = QtWidgets.QLabel(self.LogIngest)
        self.LogIngestionEnforcementLabel.setGeometry(QtCore.QRect(30, 270, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LogIngestionEnforcementLabel.setFont(font)
        self.LogIngestionEnforcementLabel.setObjectName("LogIngestionEnforcementLabel")
        self.LogIngestionCleanseLabel = QtWidgets.QLabel(self.LogIngest)
        self.LogIngestionCleanseLabel.setGeometry(QtCore.QRect(440, 16, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LogIngestionCleanseLabel.setFont(font)
        self.LogIngestionCleanseLabel.setObjectName("LogIngestionCleanseLabel")
        self.LogIngestionCleanseTable = QtWidgets.QListWidget(self.LogIngest)
        self.LogIngestionCleanseTable.setGeometry(QtCore.QRect(440, 40, 256, 101))
        self.LogIngestionCleanseTable.setObjectName("LogIngestionCleanseTable")
        item = QtWidgets.QListWidgetItem()
        self.LogIngestionCleanseTable.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.LogIngestionCleanseTable.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.LogIngestionCleanseTable.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.LogIngestionCleanseTable.addItem(item)
        self.MainPageTabWidget.addTab(self.LogIngest, "")
        self.LogEntries = QtWidgets.QWidget()
        self.LogEntries.setObjectName("LogEntries")
        self.LogEntriesTable = QtWidgets.QTableWidget(self.LogEntries)
        self.LogEntriesTable.setGeometry(QtCore.QRect(25, 51, 751, 411))
        self.LogEntriesTable.setObjectName("LogEntriesTable")
        self.LogEntriesTable.setColumnCount(7)
        self.LogEntriesTable.setRowCount(15)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setItem(2, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.LogEntriesTable.setItem(4, 1, item)
        self.LogEntriesAssociateBtn = QtWidgets.QPushButton(self.LogEntries)
        self.LogEntriesAssociateBtn.setGeometry(QtCore.QRect(684, 470, 91, 31))
        self.LogEntriesAssociateBtn.setObjectName("LogEntriesAssociateBtn")
        self.LogEntriesAssociateBtn.clicked.connect(self.showAssociateVectorScreen)
        self.LogEntriesMarkSigBtn = QtWidgets.QPushButton(self.LogEntries)
        self.LogEntriesMarkSigBtn.setGeometry(QtCore.QRect(560, 470, 121, 31))
        self.LogEntriesMarkSigBtn.setObjectName("LogEntriesMarkSigBtn")
        self.LogEntriesFilterBtn = QtWidgets.QPushButton(self.LogEntries)
        self.LogEntriesFilterBtn.setGeometry(QtCore.QRect(480, 470, 81, 31))
        self.LogEntriesFilterBtn.setObjectName("LogEntriesFilterBtn")
        self.LogEntriesFilterBtn.clicked.connect(self.showFilterScreen)
        self.LogEntriesLabel = QtWidgets.QLabel(self.LogEntries)
        self.LogEntriesLabel.setGeometry(QtCore.QRect(30, 30, 81, 16))
        self.LogEntriesLabel.setObjectName("LogEntriesLabel")
        self.MainPageTabWidget.addTab(self.LogEntries, "")
        self.VectorView = QtWidgets.QWidget()
        self.VectorView.setObjectName("VectorView")
        self.VectorViewVectorTable = QtWidgets.QTableWidget(self.VectorView)
        self.VectorViewVectorTable.setGeometry(QtCore.QRect(10, 61, 451, 321))
        self.VectorViewVectorTable.setObjectName("VectorViewVectorTable")
        self.VectorViewVectorTable.setColumnCount(10)
        self.VectorViewVectorTable.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewVectorTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewVectorTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewVectorTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewVectorTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewVectorTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewVectorTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewVectorTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewVectorTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewVectorTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewVectorTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewVectorTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewVectorTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewVectorTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewVectorTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewVectorTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewVectorTable.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewVectorTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewVectorTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewVectorTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewVectorTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewVectorTable.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewVectorTable.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewVectorTable.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewVectorTable.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewVectorTable.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewVectorTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewVectorTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewVectorTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewVectorTable.setItem(3, 0, item)
        self.VectorViewCommitBtn = QtWidgets.QPushButton(self.VectorView)
        self.VectorViewCommitBtn.setGeometry(QtCore.QRect(230, 390, 75, 23))
        self.VectorViewCommitBtn.setObjectName("VectorViewCommitBtn")
        self.VectorViewDisconnectBtn = QtWidgets.QPushButton(self.VectorView)
        self.VectorViewDisconnectBtn.setGeometry(QtCore.QRect(300, 390, 91, 23))
        self.VectorViewDisconnectBtn.setObjectName("VectorViewDisconnectBtn")
        self.VectorViewDisconnectBtn.clicked.connect(self.dissconnectedPopup)
        self.VectorViewConnectBtn = QtWidgets.QPushButton(self.VectorView)
        self.VectorViewConnectBtn.setGeometry(QtCore.QRect(390, 390, 75, 23))
        self.VectorViewConnectBtn.setObjectName("VectorViewConnectBtn")
        self.VectorViewConnectBtn.clicked.connect(self.showDetectingChanges)
        self.VectorViewRedoBtn = QtWidgets.QPushButton(self.VectorView)
        self.VectorViewRedoBtn.setGeometry(QtCore.QRect(770, 390, 75, 23))
        self.VectorViewRedoBtn.setObjectName("VectorViewRedoBtn")
        self.VectorViewUndoBtn = QtWidgets.QPushButton(self.VectorView)
        self.VectorViewUndoBtn.setGeometry(QtCore.QRect(670, 390, 75, 23))
        self.VectorViewUndoBtn.setObjectName("VectorViewUndoBtn")
        self.VectorViewVectorComBox = QtWidgets.QComboBox(self.VectorView)
        self.VectorViewVectorComBox.setGeometry(QtCore.QRect(10, 40, 181, 21))
        self.VectorViewVectorComBox.setObjectName("VectorViewVectorComBox")
        self.VectorViewVectorComBox.addItem("")
        self.VectorViewVectorComBox.addItem("")
        self.widget = QtWidgets.QWidget(self.VectorView)
        self.widget.setGeometry(QtCore.QRect(10, 260, 120, 80))
        self.widget.setObjectName("widget")
        self.VectorViewGraphView = QtWidgets.QGraphicsView(self.VectorView)
        self.VectorViewGraphView.setGeometry(QtCore.QRect(490, 60, 361, 321))
        self.VectorViewGraphView.setObjectName("VectorViewGraphView")
        self.VectorViewAddNodeBtn = QtWidgets.QPushButton(self.VectorView)
        self.VectorViewAddNodeBtn.setGeometry(QtCore.QRect(604, 30, 91, 23))
        self.VectorViewAddNodeBtn.setObjectName("VectorViewAddNodeBtn")
        self.VectorViewExportGraphBtn = QtWidgets.QPushButton(self.VectorView)
        self.VectorViewExportGraphBtn.setGeometry(QtCore.QRect(480, 30, 101, 23))
        self.VectorViewExportGraphBtn.setObjectName("VectorViewExportGraphBtn")
        self.VectorViewExportGraphBtn.clicked.connect(self.showExportGraphScreen)
        self.VectorViewRelationshipTable = QtWidgets.QTableWidget(self.VectorView)
        self.VectorViewRelationshipTable.setGeometry(QtCore.QRect(490, 420, 361, 131))
        self.VectorViewRelationshipTable.setObjectName("VectorViewRelationshipTable")
        self.VectorViewRelationshipTable.setColumnCount(4)
        self.VectorViewRelationshipTable.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewRelationshipTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewRelationshipTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewRelationshipTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewRelationshipTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewRelationshipTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewRelationshipTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewRelationshipTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewRelationshipTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewRelationshipTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewRelationshipTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewRelationshipTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewRelationshipTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewRelationshipTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewRelationshipTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewRelationshipTable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorViewRelationshipTable.setItem(1, 3, item)
        self.VectorViewZoomBtn = QtWidgets.QPushButton(self.VectorView)
        self.VectorViewZoomBtn.setGeometry(QtCore.QRect(690, 30, 71, 23))
        self.VectorViewZoomBtn.setObjectName("VectorViewZoomBtn")
        self.VectorViewZoomOutBtn = QtWidgets.QPushButton(self.VectorView)
        self.VectorViewZoomOutBtn.setGeometry(QtCore.QRect(760, 30, 91, 23))
        self.VectorViewZoomOutBtn.setObjectName("VectorViewZoomOutBtn")
        self.MainPageTabWidget.addTab(self.VectorView, "")
        self.History = QtWidgets.QWidget()
        self.History.setObjectName("History")
        self.HistoryTable = QtWidgets.QTableWidget(self.History)
        self.HistoryTable.setGeometry(QtCore.QRect(10, 50, 411, 341))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HistoryTable.sizePolicy().hasHeightForWidth())
        self.HistoryTable.setSizePolicy(sizePolicy)
        self.HistoryTable.setObjectName("HistoryTable")
        self.HistoryTable.setColumnCount(4)
        self.HistoryTable.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.HistoryTable.setItem(3, 3, item)
        self.HistoryActionLabel = QtWidgets.QLabel(self.History)
        self.HistoryActionLabel.setGeometry(QtCore.QRect(10, 30, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.HistoryActionLabel.setFont(font)
        self.HistoryActionLabel.setObjectName("HistoryActionLabel")
        self.HistorySearchBar = QtWidgets.QTextEdit(self.History)
        self.HistorySearchBar.setGeometry(QtCore.QRect(250, 21, 161, 20))
        self.HistorySearchBar.setObjectName("HistorySearchBar")
        self.MainPageTabWidget.addTab(self.History, "")
        self.Lead = QtWidgets.QWidget()
        self.Lead.setObjectName("Lead")
        self.LeadVectorChangesTable = QtWidgets.QTableWidget(self.Lead)
        self.LeadVectorChangesTable.setGeometry(QtCore.QRect(10, 40, 411, 331))
        self.LeadVectorChangesTable.setObjectName("LeadVectorChangesTable")
        self.LeadVectorChangesTable.setColumnCount(4)
        self.LeadVectorChangesTable.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.LeadVectorChangesTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.LeadVectorChangesTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.LeadVectorChangesTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.LeadVectorChangesTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.LeadVectorChangesTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.LeadVectorChangesTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.LeadVectorChangesTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.LeadVectorChangesTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.LeadVectorChangesTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.LeadVectorChangesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.LeadVectorChangesTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.LeadVectorChangesTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.LeadVectorChangesTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.LeadVectorChangesTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.LeadVectorChangesTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.LeadVectorChangesTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.LeadVectorChangesTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.LeadVectorChangesTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.LeadVectorChangesTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.LeadVectorChangesTable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.LeadVectorChangesTable.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.LeadVectorChangesTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.LeadVectorChangesTable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.LeadVectorChangesTable.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.LeadVectorChangesTable.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.LeadVectorChangesTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.LeadVectorChangesTable.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.LeadVectorChangesTable.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.LeadVectorChangesTable.setItem(3, 3, item)
        self.LeadNotificationsTable = QtWidgets.QTextEdit(self.Lead)
        self.LeadNotificationsTable.setGeometry(QtCore.QRect(470, 40, 371, 321))
        self.LeadNotificationsTable.setObjectName("LeadNotificationsTable")
        self.LeadNotificationsAcceptBtn = QtWidgets.QPushButton(self.Lead)
        self.LeadNotificationsAcceptBtn.setGeometry(QtCore.QRect(480, 320, 75, 23))
        self.LeadNotificationsAcceptBtn.setObjectName("LeadNotificationsAcceptBtn")
        self.LeadNotificationsDenyBtn = QtWidgets.QPushButton(self.Lead)
        self.LeadNotificationsDenyBtn.setGeometry(QtCore.QRect(760, 320, 75, 23))
        self.LeadNotificationsDenyBtn.setObjectName("LeadNotificationsDenyBtn")
        self.LeadNotificationsDenyBtn.clicked.connect(self.showDenyDialog)
        self.LeadVectorChangesLabel = QtWidgets.QLabel(self.Lead)
        self.LeadVectorChangesLabel.setGeometry(QtCore.QRect(10, 20, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LeadVectorChangesLabel.setFont(font)
        self.LeadVectorChangesLabel.setObjectName("LeadVectorChangesLabel")
        self.HistoryNotificationsLabel = QtWidgets.QLabel(self.Lead)
        self.HistoryNotificationsLabel.setGeometry(QtCore.QRect(470, 20, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.HistoryNotificationsLabel.setFont(font)
        self.HistoryNotificationsLabel.setObjectName("HistoryNotificationsLabel")
        self.MainPageTabWidget.addTab(self.Lead, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 886, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.MainPageTabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.EventConfigBrowseBtn.setText(_translate("MainWindow", "Browse"))
        __sortingEnabled = self.EventConfigAnalystList.isSortingEnabled()
        self.EventConfigAnalystList.setSortingEnabled(False)
        item = self.EventConfigAnalystList.item(0)
        item.setText(_translate("MainWindow", "Analyst 1"))
        item = self.EventConfigAnalystList.item(1)
        item.setText(_translate("MainWindow", "Analyst 2"))
        item = self.EventConfigAnalystList.item(2)
        item.setText(_translate("MainWindow", "Analyst 3"))
        self.EventConfigAnalystList.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.EventConfigVectorList.isSortingEnabled()
        self.EventConfigVectorList.setSortingEnabled(False)
        item = self.EventConfigVectorList.item(0)
        item.setText(_translate("MainWindow", "Vector 1"))
        item = self.EventConfigVectorList.item(1)
        item.setText(_translate("MainWindow", "Vector 2"))
        item = self.EventConfigVectorList.item(2)
        item.setText(_translate("MainWindow", "Vector 3"))
        item = self.EventConfigVectorList.item(3)
        item.setText(_translate("MainWindow", "Vector n"))
        self.EventConfigVectorList.setSortingEnabled(__sortingEnabled)
        self.AddVectorBtn.setText(_translate("MainWindow", "Add Vector"))
        self.RemoveVectorBtn.setText(_translate("MainWindow", "Remove Vector"))
        self.EventConfigBackBtn.setText(_translate("MainWindow", "Back"))
        self.EventConfigSaveBtn.setText(_translate("MainWindow", "Save"))
        self.EventConfigDescription.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">Description</span></p></body></html>"))
        self.EventConfigNameEdit.setText(_translate("MainWindow", "Name"))
        self.EventConfigStartDateLabel.setText(_translate("MainWindow", "Start Date"))
        self.EventConfigEndDateLabel.setText(_translate("MainWindow", "End Date"))
        self.EventConfigStartTimeLabel.setText(_translate("MainWindow", "Start Time"))
        self.EventConfigEndTimeLabel.setText(_translate("MainWindow", "End Time"))
        self.EventConfigRootDirLabel.setText(_translate("MainWindow", "Root Directory"))
        self.label.setText(_translate("MainWindow", "General Event Information:"))
        self.label_2.setText(_translate("MainWindow", "Root Directory Configuartion:"))
        self.MainPageTabWidget.setTabText(self.MainPageTabWidget.indexOf(self.EventConfig), _translate("MainWindow", "Event Config"))
        self.LogIngestionIngestBtn.setText(_translate("MainWindow", "Ingest"))
        self.LogIngestionImportLogBtn.setText(_translate("MainWindow", "Import Log"))
        self.LogIngestionIgnoreBtn.setText(_translate("MainWindow", "Ignore"))
        self.LogIngestionConfirmBtn.setText(_translate("MainWindow", "Confirm"))
        item = self.LogIngestionWaitingTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Log"))
        item = self.LogIngestionWaitingTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Time"))
        item = self.LogIngestionWaitingTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Description"))
        item = self.LogIngestionWaitingTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Team"))
        item = self.LogIngestionWaitingTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Progress"))
        item = self.LogIngestionWaitingTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Status"))
        __sortingEnabled = self.LogIngestionWaitingTable.isSortingEnabled()
        self.LogIngestionWaitingTable.setSortingEnabled(False)
        item = self.LogIngestionWaitingTable.item(0, 1)
        item.setText(_translate("MainWindow", "Log A"))
        item = self.LogIngestionWaitingTable.item(1, 1)
        item.setText(_translate("MainWindow", "Log B"))
        item = self.LogIngestionWaitingTable.item(2, 1)
        item.setText(_translate("MainWindow", "Log C"))
        item = self.LogIngestionWaitingTable.item(3, 1)
        item.setText(_translate("MainWindow", "Log D"))
        self.LogIngestionWaitingTable.setSortingEnabled(__sortingEnabled)
        item = self.LogIngestionEnforcementTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Log A"))
        item = self.LogIngestionEnforcementTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Log B"))
        item = self.LogIngestionEnforcementTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Log C"))
        item = self.LogIngestionEnforcementTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Log D"))
        item = self.LogIngestionEnforcementTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Log X"))
        item = self.LogIngestionEnforcementTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Log K"))
        item = self.LogIngestionEnforcementTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Log"))
        item = self.LogIngestionEnforcementTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time"))
        item = self.LogIngestionEnforcementTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Description"))
        item = self.LogIngestionEnforcementTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Team"))
        item = self.LogIngestionEnforcementTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Error"))
        self.LogIngestionWaitingValiLabel.setText(_translate("MainWindow", "Logs Waiting for Validation"))
        self.LogIngestionEnforcementLabel.setText(_translate("MainWindow", "Enforcement Action Report"))
        self.LogIngestionCleanseLabel.setText(_translate("MainWindow", "Cleansed Files"))
        __sortingEnabled = self.LogIngestionCleanseTable.isSortingEnabled()
        self.LogIngestionCleanseTable.setSortingEnabled(False)
        item = self.LogIngestionCleanseTable.item(0)
        item.setText(_translate("MainWindow", "Log A"))
        item = self.LogIngestionCleanseTable.item(1)
        item.setText(_translate("MainWindow", "Log C"))
        item = self.LogIngestionCleanseTable.item(2)
        item.setText(_translate("MainWindow", "Log X"))
        self.LogIngestionCleanseTable.setSortingEnabled(__sortingEnabled)
        self.MainPageTabWidget.setTabText(self.MainPageTabWidget.indexOf(self.LogIngest), _translate("MainWindow", "Log Ingestion"))
        item = self.LogEntriesTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Log ID"))
        item = self.LogEntriesTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Log Name"))
        item = self.LogEntriesTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Time Stamp"))
        item = self.LogEntriesTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Description"))
        item = self.LogEntriesTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Reporter"))
        item = self.LogEntriesTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Origin Document"))
        item = self.LogEntriesTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Team"))
        __sortingEnabled = self.LogEntriesTable.isSortingEnabled()
        self.LogEntriesTable.setSortingEnabled(False)
        item = self.LogEntriesTable.item(0, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.LogEntriesTable.item(0, 1)
        item.setText(_translate("MainWindow", "Log A"))
        item = self.LogEntriesTable.item(0, 2)
        item.setText(_translate("MainWindow", "11:40"))
        item = self.LogEntriesTable.item(0, 3)
        item.setText(_translate("MainWindow", "Red Team Attack"))
        item = self.LogEntriesTable.item(0, 4)
        item.setText(_translate("MainWindow", "White Team"))
        item = self.LogEntriesTable.item(0, 5)
        item.setText(_translate("MainWindow", "Report1.txt"))
        item = self.LogEntriesTable.item(0, 6)
        item.setText(_translate("MainWindow", "Red "))
        item = self.LogEntriesTable.item(1, 0)
        item.setText(_translate("MainWindow", "2"))
        item = self.LogEntriesTable.item(1, 1)
        item.setText(_translate("MainWindow", "Log B"))
        item = self.LogEntriesTable.item(1, 2)
        item.setText(_translate("MainWindow", "10:38"))
        item = self.LogEntriesTable.item(1, 3)
        item.setText(_translate("MainWindow", "Notice Attack"))
        item = self.LogEntriesTable.item(1, 4)
        item.setText(_translate("MainWindow", "White Team"))
        item = self.LogEntriesTable.item(1, 5)
        item.setText(_translate("MainWindow", "Report2.txt"))
        item = self.LogEntriesTable.item(1, 6)
        item.setText(_translate("MainWindow", "Blue"))
        item = self.LogEntriesTable.item(2, 0)
        item.setText(_translate("MainWindow", "3"))
        item = self.LogEntriesTable.item(2, 1)
        item.setText(_translate("MainWindow", "Log X"))
        item = self.LogEntriesTable.item(2, 2)
        item.setText(_translate("MainWindow", "..."))
        item = self.LogEntriesTable.item(2, 3)
        item.setText(_translate("MainWindow", "..."))
        item = self.LogEntriesTable.item(2, 4)
        item.setText(_translate("MainWindow", "..."))
        item = self.LogEntriesTable.item(2, 5)
        item.setText(_translate("MainWindow", "..."))
        item = self.LogEntriesTable.item(2, 6)
        item.setText(_translate("MainWindow", "..."))
        self.LogEntriesTable.setSortingEnabled(__sortingEnabled)
        self.LogEntriesAssociateBtn.setText(_translate("MainWindow", "Associate"))
        self.LogEntriesMarkSigBtn.setText(_translate("MainWindow", "Mark Significant"))
        self.LogEntriesFilterBtn.setText(_translate("MainWindow", "Filter"))
        self.LogEntriesLabel.setText(_translate("MainWindow", "Log Entries"))
        self.MainPageTabWidget.setTabText(self.MainPageTabWidget.indexOf(self.LogEntries), _translate("MainWindow", "Log Entries"))
        item = self.VectorViewVectorTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.VectorViewVectorTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.VectorViewVectorTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "TOC"))
        item = self.VectorViewVectorTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Description"))
        item = self.VectorViewVectorTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Reference"))
        item = self.VectorViewVectorTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Creator"))
        item = self.VectorViewVectorTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Event"))
        item = self.VectorViewVectorTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Icon Type"))
        item = self.VectorViewVectorTable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Artifact"))
        item = self.VectorViewVectorTable.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Visibility"))
        __sortingEnabled = self.VectorViewVectorTable.isSortingEnabled()
        self.VectorViewVectorTable.setSortingEnabled(False)
        item = self.VectorViewVectorTable.item(0, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.VectorViewVectorTable.item(0, 1)
        item.setText(_translate("MainWindow", "11:40"))
        item = self.VectorViewVectorTable.item(0, 2)
        item.setText(_translate("MainWindow", "Red Team Attack"))
        item = self.VectorViewVectorTable.item(0, 3)
        item.setText(_translate("MainWindow", "Report1.txt"))
        item = self.VectorViewVectorTable.item(0, 4)
        item.setText(_translate("MainWindow", "Red Team"))
        item = self.VectorViewVectorTable.item(0, 5)
        item.setText(_translate("MainWindow", "Red"))
        item = self.VectorViewVectorTable.item(0, 6)
        item.setText(_translate("MainWindow", "Red"))
        item = self.VectorViewVectorTable.item(0, 7)
        item.setText(_translate("MainWindow", "File01.jpg"))
        item = self.VectorViewVectorTable.item(0, 8)
        item.setText(_translate("MainWindow", "notes.csv"))
        item = self.VectorViewVectorTable.item(1, 0)
        item.setText(_translate("MainWindow", "2"))
        item = self.VectorViewVectorTable.item(1, 1)
        item.setText(_translate("MainWindow", "10:38"))
        item = self.VectorViewVectorTable.item(2, 0)
        item.setText(_translate("MainWindow", "3"))
        item = self.VectorViewVectorTable.item(3, 0)
        item.setText(_translate("MainWindow", "n"))
        self.VectorViewVectorTable.setSortingEnabled(__sortingEnabled)
        self.VectorViewCommitBtn.setText(_translate("MainWindow", "Commit"))
        self.VectorViewDisconnectBtn.setText(_translate("MainWindow", "Disconnect"))
        self.VectorViewConnectBtn.setText(_translate("MainWindow", "Connect"))
        self.VectorViewRedoBtn.setText(_translate("MainWindow", "REDO"))
        self.VectorViewUndoBtn.setText(_translate("MainWindow", "UNDO"))
        self.VectorViewVectorComBox.setItemText(0, _translate("MainWindow", "Vector 1"))
        self.VectorViewVectorComBox.setItemText(1, _translate("MainWindow", "Vector 2"))
        self.VectorViewAddNodeBtn.setText(_translate("MainWindow", "Add Node"))
        self.VectorViewExportGraphBtn.setText(_translate("MainWindow", "Export Graph"))
        item = self.VectorViewRelationshipTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Relationship"))
        item = self.VectorViewRelationshipTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Parent"))
        item = self.VectorViewRelationshipTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Children"))
        item = self.VectorViewRelationshipTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Label"))
        __sortingEnabled = self.VectorViewRelationshipTable.isSortingEnabled()
        self.VectorViewRelationshipTable.setSortingEnabled(False)
        item = self.VectorViewRelationshipTable.item(0, 0)
        item.setText(_translate("MainWindow", "R-001"))
        item = self.VectorViewRelationshipTable.item(0, 1)
        item.setText(_translate("MainWindow", "1-001"))
        item = self.VectorViewRelationshipTable.item(0, 2)
        item.setText(_translate("MainWindow", "1-002"))
        item = self.VectorViewRelationshipTable.item(0, 3)
        item.setText(_translate("MainWindow", "Exploit"))
        item = self.VectorViewRelationshipTable.item(1, 0)
        item.setText(_translate("MainWindow", "R-002"))
        item = self.VectorViewRelationshipTable.item(1, 1)
        item.setText(_translate("MainWindow", "1-002"))
        item = self.VectorViewRelationshipTable.item(1, 2)
        item.setText(_translate("MainWindow", "1-003"))
        item = self.VectorViewRelationshipTable.item(1, 3)
        item.setText(_translate("MainWindow", "Response"))
        self.VectorViewRelationshipTable.setSortingEnabled(__sortingEnabled)
        self.VectorViewZoomBtn.setText(_translate("MainWindow", "Zoom"))
        self.VectorViewZoomOutBtn.setText(_translate("MainWindow", "Zoom-out"))
        self.MainPageTabWidget.setTabText(self.MainPageTabWidget.indexOf(self.VectorView), _translate("MainWindow", "Vector View"))
        item = self.HistoryTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Creator"))
        item = self.HistoryTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Action"))
        item = self.HistoryTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Time"))
        item = self.HistoryTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Date"))
        __sortingEnabled = self.HistoryTable.isSortingEnabled()
        self.HistoryTable.setSortingEnabled(False)
        item = self.HistoryTable.item(0, 0)
        item.setText(_translate("MainWindow", "Analyst 1"))
        item = self.HistoryTable.item(0, 1)
        item.setText(_translate("MainWindow", "Edit log entry x"))
        item = self.HistoryTable.item(0, 2)
        item.setText(_translate("MainWindow", "11:40"))
        item = self.HistoryTable.item(0, 3)
        item.setText(_translate("MainWindow", "10-14-2019"))
        item = self.HistoryTable.item(1, 0)
        item.setText(_translate("MainWindow", "Analyst 3"))
        item = self.HistoryTable.item(1, 1)
        item.setText(_translate("MainWindow", "Added node to Vector x"))
        item = self.HistoryTable.item(1, 2)
        item.setText(_translate("MainWindow", "10:38"))
        item = self.HistoryTable.item(1, 3)
        item.setText(_translate("MainWindow", "10-14-2019"))
        item = self.HistoryTable.item(2, 0)
        item.setText(_translate("MainWindow", "Analyst 2"))
        item = self.HistoryTable.item(2, 1)
        item.setText(_translate("MainWindow", "Added a node to graph"))
        item = self.HistoryTable.item(2, 2)
        item.setText(_translate("MainWindow", "12:41"))
        item = self.HistoryTable.item(2, 3)
        item.setText(_translate("MainWindow", "10-13-2019"))
        item = self.HistoryTable.item(3, 0)
        item.setText(_translate("MainWindow", "Analyst n"))
        item = self.HistoryTable.item(3, 1)
        item.setText(_translate("MainWindow", "Connected node x and node y"))
        item = self.HistoryTable.item(3, 2)
        item.setText(_translate("MainWindow", "2:29"))
        item = self.HistoryTable.item(3, 3)
        item.setText(_translate("MainWindow", "10-13-2019"))
        self.HistoryTable.setSortingEnabled(__sortingEnabled)
        self.HistoryActionLabel.setText(_translate("MainWindow", "Actions"))
        self.HistorySearchBar.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">Search</span></p></body></html>"))
        self.MainPageTabWidget.setTabText(self.MainPageTabWidget.indexOf(self.History), _translate("MainWindow", "History"))
        item = self.LeadVectorChangesTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Creator"))
        item = self.LeadVectorChangesTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time"))
        item = self.LeadVectorChangesTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date"))
        item = self.LeadVectorChangesTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Description"))
        __sortingEnabled = self.LeadVectorChangesTable.isSortingEnabled()
        self.LeadVectorChangesTable.setSortingEnabled(False)
        item = self.LeadVectorChangesTable.item(0, 0)
        item.setText(_translate("MainWindow", "Analyst 1"))
        item = self.LeadVectorChangesTable.item(0, 1)
        item.setText(_translate("MainWindow", "11:40"))
        item = self.LeadVectorChangesTable.item(0, 2)
        item.setText(_translate("MainWindow", "10-14-2019"))
        item = self.LeadVectorChangesTable.item(0, 3)
        item.setText(_translate("MainWindow", "Change Vector Name"))
        item = self.LeadVectorChangesTable.item(1, 0)
        item.setText(_translate("MainWindow", "Analyst 2"))
        item = self.LeadVectorChangesTable.item(1, 1)
        item.setText(_translate("MainWindow", "12:39"))
        item = self.LeadVectorChangesTable.item(1, 2)
        item.setText(_translate("MainWindow", "10-14-2019"))
        item = self.LeadVectorChangesTable.item(1, 3)
        item.setText(_translate("MainWindow", "Added new nodes in vector x"))
        item = self.LeadVectorChangesTable.item(2, 0)
        item.setText(_translate("MainWindow", "Analyst 4"))
        item = self.LeadVectorChangesTable.item(2, 1)
        item.setText(_translate("MainWindow", "1:45"))
        item = self.LeadVectorChangesTable.item(2, 2)
        item.setText(_translate("MainWindow", "10-13-2019"))
        item = self.LeadVectorChangesTable.item(2, 3)
        item.setText(_translate("MainWindow", "..."))
        item = self.LeadVectorChangesTable.item(3, 0)
        item.setText(_translate("MainWindow", "Analyst n"))
        item = self.LeadVectorChangesTable.item(3, 1)
        item.setText(_translate("MainWindow", "3:45"))
        item = self.LeadVectorChangesTable.item(3, 2)
        item.setText(_translate("MainWindow", "10-130-2019"))
        item = self.LeadVectorChangesTable.item(3, 3)
        item.setText(_translate("MainWindow", "..."))
        self.LeadVectorChangesTable.setSortingEnabled(__sortingEnabled)
        self.LeadNotificationsTable.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600; text-decoration: underline;\">Change 1</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">...</span></p></body></html>"))
        self.LeadNotificationsAcceptBtn.setText(_translate("MainWindow", "Accept"))
        self.LeadNotificationsDenyBtn.setText(_translate("MainWindow", "Deny"))
        self.LeadVectorChangesLabel.setText(_translate("MainWindow", "Vector DB Changes"))
        self.HistoryNotificationsLabel.setText(_translate("MainWindow", "Notifications"))
        self.MainPageTabWidget.setTabText(self.MainPageTabWidget.indexOf(self.Lead), _translate("MainWindow", "Lead"))

    def dissconnectedPopup(self):
        msg = QMessageBox()
        msg.setWindowTitle("Disconnected")
        msg.setText("Download is complete")
        msg.setIcon(QMessageBox.Information)
        msg.setStandardButtons(QMessageBox.Ok)
        x = msg.exec_()


    def showAddVectorDialog(self):
        self.window = QtWidgets.QDialog()
        self.ui = addVectorDialog()
        self.ui.setupUi(self.window)
        self.window.show()

    def showDenyDialog(self):
        self.window = QtWidgets.QDialog()
        self.ui = DenyDialog()
        self.ui.setupUi(self.window)
        self.window.show()

    def showFilterScreen(self):
        self.window = QtWidgets.QDialog()
        self.ui = FilterScreen()
        self.ui.setupUi(self.window)
        self.window.show()

    def showBrowseScreen(self):
        self.window = QtWidgets.QDialog()
        self.ui = BrowseScreen()
        self.ui.setupUi(self.window)
        self.window.show()

    def showAssociateVectorScreen(self):
        self.window = QtWidgets.QDialog()
        self.ui = AssociateVectorScreen()
        self.ui.setupUi(self.window)
        self.window.show()

    def showDetectingChanges(self):
        self.window = QtWidgets.QDialog()
        self.ui = DetectingChangesScreen()
        self.ui.setupUi(self.window)
        self.window.show()

    def showExportGraphScreen(self):
        self.window = QtWidgets.QDialog()
        self.ui = ExportGraphScreen()
        self.ui.setupUi(self.window)
        self.window.show()




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = MainScreen()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
